[package]
name = "day_4"
version = "0.1.0"
authors = ["Markus Suomalainen <markus.suomalainen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fancy-regex = "0.3.1"
